// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QAEngine.Persistence;

namespace QAEngine.Persistence.Migrations
{
    [DbContext(typeof(QAEngineDbContext))]
    [Migration("20181010113834_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QAEngine.Domain.Entities.Customer", b =>
                {
                    b.Property<string>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CustomerID")
                        .HasMaxLength(8);

                    b.Property<DateTime>("AccountCreated");

                    b.Property<string>("Address")
                        .HasColumnName("Address")
                        .HasMaxLength(45);

                    b.Property<string>("City")
                        .HasColumnName("City")
                        .HasMaxLength(15);

                    b.Property<string>("Country")
                        .HasColumnName("Country")
                        .HasMaxLength(15);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnName("DateOfBirth");

                    b.Property<string>("FirstName")
                        .HasColumnName("FirstName")
                        .HasMaxLength(10);

                    b.Property<string>("LastName")
                        .HasColumnName("LastName")
                        .HasMaxLength(10);

                    b.Property<string>("Phone")
                        .HasColumnName("Phone")
                        .HasMaxLength(15);

                    b.Property<string>("PostalCode")
                        .HasColumnName("PostalCode")
                        .HasMaxLength(6);

                    b.Property<string>("Region")
                        .HasColumnName("Region")
                        .HasMaxLength(20);

                    b.Property<string>("Title")
                        .HasColumnName("Title")
                        .HasMaxLength(5);

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
